name: "Android Kernel Builder"
description: "Reliable CI action to build Android kernels with packaging and release support."

branding:
  icon: "activity"
  color: "blue"

inputs:

  clone-depth:
    default: "1"

  kernel-url:
    required: true

  kernel-branch:
    required: true

  defconfig:
    default: "defconfig"
    required: true

  arch:
    default: "arm64"
    required: true

  install-commands:
    default: "binutils git make bc bison openssl curl zip kmod cpio flex libelf-dev libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-certificates python3 xz-utils libc6-dev aria2 build-essential pigz coccinelle parallel"

  extended-build-commands:
    default: ""

  use-clang:
    default: "false"

  aosp-clang-android-version:
    default: ""
  
  aosp-clang-version:
    default: ""
  
  custom-clang-url:
    default: ""

  custom-clang-branch:
    default: ""

  use-gcc:
    default: "false"

  aosp-gcc-android-version:
    default: ""

  custom-gcc-url:
    default: ""
  
  custom-gcc-branch:
    default: ""

  use-ccache:
    default: "false"

  show-ccache-stats:
    default: "false"

  use-ksu:
    default: "false"

  ksu-url-setup:
    default: "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh"

  ksu-version:
    default: ""

  use-anykernel3:
    default: "false"

  release:
    default: "false"

  release-name:
    default: "KernelBuild"
  
  use-extended-release-name:
    default: "false"

  access-token:
    required: false

runs:
  using: "composite"

  steps:

    # ----------------------------
    # INIT
    # ----------------------------
    - name: Init
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p build

        echo "::group:: ⚙️ Saving Inputs to GITHUB_ENV"
        # kernel build
        echo "CLONE_DEPTH=${{ inputs.clone-depth }}" >> $GITHUB_ENV
        echo "KERNEL_URL=${{ inputs.kernel-url }}" >> $GITHUB_ENV
        echo "KERNEL_BRANCH=${{ inputs.kernel-branch }}" >> $GITHUB_ENV
        echo "DEFCONFIG=${{ inputs.defconfig }}" >> $GITHUB_ENV
        echo "ARCH=${{ inputs.arch }}" >> $GITHUB_ENV

        echo "INSTALL_COMMANDS=${{ inputs.install-commands }}" >> $GITHUB_ENV
        echo "EXTENDED_BUILD_COMMANDS=${{ inputs.extended-build-commands }}" >> $GITHUB_ENV
        
        # clang
        echo "USE_CLANG=${{ inputs.use-clang }}" >> $GITHUB_ENV
        echo "AOSP_CLANG_ANDROID_VERSION=${{ inputs.aosp-clang-android-version }}" >> $GITHUB_ENV
        echo "AOSP_CLANG_VERSION=${{ inputs.aosp-clang-version }}" >> $GITHUB_ENV
        echo "CUSTOM_CLANG_URL=${{ inputs.custom-clang-url }}" >> $GITHUB_ENV
        echo "CUSTOM_CLANG_BRANCH=${{ inputs.custom-clang-branch }}" >> $GITHUB_ENV
        
        # gcc
        echo "USE_GCC=${{ inputs.use-gcc }}" >> $GITHUB_ENV
        echo "AOSP_GCC_ANDROID_VERSION=${{ inputs.aosp-gcc-android-version }}" >> $GITHUB_ENV
        echo "CUSTOM_GCC_URL=${{ inputs.custom-gcc-url }}" >> $GITHUB_ENV
        echo "CUSTOM_GCC_BRANCH=${{ inputs.custom-gcc-branch }}" >> $GITHUB_ENV

        # cache
        echo "USE_CCACHE=${{ inputs.use-ccache }}" >> $GITHUB_ENV
        echo "SHOW_CCACHE_STATS=${{ inputs.show-ccache-stats }}" >> $GITHUB_ENV

        # kernelsu
        echo "USE_KSU=${{ inputs.use-ksu }}" >> $GITHUB_ENV
        echo "KSU_URL_SETUP=${{ inputs.ksu-url-setup }}" >> $GITHUB_ENV
        echo "KSU_VERSION=${{ inputs.ksu-version }}" >> $GITHUB_ENV

        # anykernel
        echo "USE_ANYKERNEL=${{ inputs.use-anykernel }}" >> $GITHUB_ENV

        # release
        echo "USE_RELEASE=${{ inputs.use-release }}" >> $GITHUB_ENV
        echo "RELEASE_NAME=${{ inputs.release-name }}" >> $GITHUB_ENV
        echo "USE_EXTENDED_RELEASE_NAME=${{ inputs.use-extended-release-name }}" >> $GITHUB_ENV
        echo "::endgroup::"
        
        echo "::group:: ⚙️ Saving Functions to functions.sh"
        cat << 'EOF' > functions.sh
        #!/usr/bin/env bash

        # download and extract files supports zip,tar,gz,xz,bz2,git
        download_and_extract() {
          local url=$1
          local output_name=$2
          local extract_dir=$3
          local branch=${4:-main}
          mkdir -p -v "$extract_dir"
          case "$url" in
            *.zip)
              aria2c -o "${output_name}.zip" "$url"
              unzip -q "${output_name}.zip" -d "$extract_dir"
              ;;
            *.tar.*|*.gz|*.xz|*.bz2)
              aria2c -o "${output_name}.${url##*.}" "$url" #${url##*.} only suitable for bash
              tar -C "$extract_dir" -xf "${output_name}.${url##*.}"
              ;;
            *)
              git clone "$url" "$extract_dir" --depth=${{ inputs.clone-depth }} -b "$branch"
              ;;
          esac
        }
        EOF
        chmod +x functions.sh
        echo "::endgroup::"

    # ----------------------------
    # DEPENDENCIES
    # ----------------------------
    - name: Install dependencies
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y $INSTALL_COMMANDS

        if [[ "$USE_CCACHE" == "true" ]]; then
          sudo apt-get install -y ccache
        fi
        if [[ -n "$USE_CLANG" ]]; then
          sudo apt-get install -y gcc-aarch64-linux-gnu
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
        fi
    # ----------------------------
    # CLANG
    # ----------------------------
    - name: Clang
      if: inputs.use-clang == 'true'
      shell: bash
      run: |
        set -euo pipefail
        source "$GITHUB_WORKSPACE/functions.sh"
        
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

        echo "::group:: ⚙️ Setup CLANG"
        if [[ -z "$CUSTOM_CLANG_URL" ]]; then
          echo "::notice:: Using AOSP clang"
          if [[ -n "$AOSP_CLANG_ANDROID_VERSION" ]]; then
            AOSP_CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android${AOSP_CLANG_ANDROID_VERSION}-release/clang-${AOSP_CLANG_VERSION}.tar.gz"
          else
            AOSP_CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/clang-${AOSP_CLANG_VERSION}.tar.gz"
          fi
          download_and_extract "$AOSP_CLANG_URL" "aosp-clang" "${PWD}/aosp-clang"
          echo "${PWD}/aosp-clang/bin" >> $GITHUB_PATH
        else
          echo "::notice:: Using Custom Clang URL"
          download_and_extract "${CUSTOM_CLANG_URL}" "custom-clang" "${PWD}/custom-clang" "${CUSTOM_CLANG_BRANCH}"
          echo "${PWD}/custom-clang/bin" >> $GITHUB_PATH
        fi
        echo "::endgroup::"

    # ----------------------------
    # GCC
    # ----------------------------
    - name: GCC
      if: inputs.use-gcc == 'true'
      shell: bash
      run: |
        set -euo pipefail
        source "$GITHUB_WORKSPACE/functions.sh"

        echo "CROSS_COMPILE=aarch64-linux-android-" >> $GITHUB_ENV
        echo "CROSS_COMPILE_ARM32=arm-linux-androideabi-" >> $GITHUB_ENV

        echo "::group:: ⚙️ Setup GCC"
        if [[ -z "${CUSTOM_GCC_URL}" ]]; then
          echo "::notice:: Downloading AOSP GCC."
          if [ -n "${AOSP_GCC_ANDROID_VERSION}" ]; then
            AOSP_GCC64_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9"
            AOSP_GCC32_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9"
            AOSP_GCC_BRANCH="android${AOSP_GCC_ANDROID_VERSION}-release"
          else
            AOSP_GCC64_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz"
            AOSP_GCC32_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz"
          fi
          download_and_extract "$AOSP_GCC64_URL" "aosp-gcc-aarch64" "${PWD}/aosp-gcc-64" "$AOSP_GCC_BRANCH"
          download_and_extract "$AOSP_GCC32_URL" "aosp-gcc-arm" "${PWD}/aosp-gcc-32" "$AOSP_GCC_BRANCH"
          echo "${PWD}/aosp-gcc-64/bin" >> $GITHUB_PATH
          echo "${PWD}/aosp-gcc-32/bin" >> $GITHUB_PATH
        else
          echo "::notice:: Using Custom GCC URL"
          download_and_extract "$CUSTOM_GCC_URL" "custom-gcc" "${PWD}/custom-gcc" "${CUSTOM_GCC_BRANCH:-main}"
          echo "${PWD}/custom-gcc/bin" >> $GITHUB_PATH
        fi

        echo "::endgroup::"
        echo "$PATH"
        echo $(ls "${PWD}/aosp-gcc-64/bin")

    # ----------------------------
    # CCACHE
    # ----------------------------
    - name: Setup ccache
      if: inputs.use-ccache == 'true'
      shell: bash
      run: |
        set -euo pipefail

        export CCACHE_DIR="$HOME/.ccache"
        export CCACHE_BASEDIR="$GITHUB_WORKSPACE"

        mkdir -p "$CCACHE_DIR"

        ccache -M 10G
        ccache -z

        echo "CCACHE_DIR=$CCACHE_DIR" >> $GITHUB_ENV
        echo "CC=ccache clang" >> $GITHUB_ENV
        echo "CXX=ccache clang++" >> $GITHUB_ENV
        # echo "HOSTCC=ccache clang" >> $GITHUB_ENV
        # echo "HOSTCXX=ccache clang++" >> $GITHUB_ENV
        # echo "CROSS_COMPILE=ccache aarch64-linux-android-" >> $GITHUB_ENV
        # echo "CROSS_COMPILE_ARM32=ccache arm-linux-androideabi-" >> $GITHUB_ENV

    # ----------------------------
    # CLONE KERNEL
    # ----------------------------
    - name: Clone kernel
      shell: bash
      run: |
        set -euo pipefail

        git clone \
          --depth=$CLONE_DEPTH \
          -b "$KERNEL_BRANCH" \
          "$KERNEL_URL" \
          target-kernel


    # ----------------------------
    # KERNELSU
    # ----------------------------
    - name: Setup KernelSU
      if: inputs.use-ksu == 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd target-kernel
        if [[ -z "$KSU_VERSION" ]]; then
          curl -fsSL "$KSU_URL_SETUP" | bash
        else
          curl -fsSL "$KSU_URL_SETUP" | bash -s "$KSU_VERSION"
        fi



    # ----------------------------
    # BUILD
    # ----------------------------
    - name: Build kernel
      shell: bash
      run: |
        set -euo pipefail
        cd target-kernel
        
        # ARCH,CROSS_COMPILE,CROSS_COMPILE_ARM32,CLANG_TRIPLE is in $GITHUB_ENV
        make -j$(nproc --all) $DEFCONFIG $EXTENDED_BUILD_COMMANDS O=out

    # ----------------------------
    # PACKAGE OUTPUTS (UNIFIED)
    # ----------------------------
    - name: Prepare artifacts
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p build

        KERNEL_OUT="target-kernel/out/arch/$ARCH/boot"

        # Copy kernel image
        if ls $KERNEL_OUT/Image* 1> /dev/null 2>&1; then
          cp $KERNEL_OUT/Image* build/
        fi

        # Copy dtb/dtbo if exist
        [ -f "$KERNEL_OUT/dtb" ] && cp "$KERNEL_OUT/dtb" build/ || true
        [ -f "$KERNEL_OUT/dtbo.img" ] && cp "$KERNEL_OUT/dtbo.img" build/ || true

    # ----------------------------
    # ANYKERNEL3 PACKAGING
    # ----------------------------
    - name: Package AnyKernel3
      if: inputs.use-anykernel3 == 'true'
      shell: bash
      run: |
        set -euo pipefail

        git clone https://github.com/osm0sis/AnyKernel3.git ak3

        cp build/* ak3/ || true

        cd ak3

        zip -r "../${{ inputs.release-name }}.zip" ./*

        cd ..
        mv "${{ inputs.release-name }}.zip" build/

    # ----------------------------
    # ARTIFACT UPLOAD
    # ----------------------------
    - name: Upload kernel artifacts
      if: inputs.release == 'false'
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build
        path: build/*

    # ----------------------------
    # ARTIFACT UPLOAD WITH ANYKERNEL
    # ----------------------------
    - name: Upload AnyKernel3 artifacts
      if: inputs.release == 'false' && inputs.use-anykernel3 == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: anykernel3-package
        path: build/*

    # ----------------------------
    # RELEASE
    # ----------------------------
    - name: Create Release
      if: inputs.release == 'true'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ inputs.access-token }}
      with:
        name: ${{ inputs.release-name }}
        tag_name: ${{ inputs.release-name }}-${{ github.sha }}
        files: build/*
        make_latest: true